name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, "8.0", 8.1, 8.2, 8.3]
        symfony_process: [4, 5, 6, 7]
        exclude:
          - php: 7.3
            symfony_process: 6
          - php: 7.4
            symfony_process: 6
          - php: 7.3
            symfony_process: 7
          - php: 7.4
            symfony_process: 7
          - php: "8.0"
            symfony_process: 7
          - php: 8.1
            symfony_process: 7

    steps:
      - uses: actions/checkout@v4

      - name: test against Symfony/Process ${{ matrix.symfony_process }} on PHP ${{ matrix.php }}
        run: docker build . --build-arg PHP_VERSION=${{ matrix.php }} --build-arg SYMFONY_PROCESS=${{ matrix.symfony_process }}
